# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hilt Text Analysis 2016
# email: scott.enderle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    The syllabus form Katie Rawson and Scott Enderle's 2016 Text Analysis 
    class, including links to instructions, notebooks, and datasets.
baseurl: "/hilt-text-analysis" # the subpath of your site, e.g. /blog
url: "http://senderle.github.io" # the base hostname & protocol for your site
authors:
    senderle:
        name: Scott Enderle
        display_name: Scott
        twitter: senderle
        github: senderle
    krawson:
        name: Katie Rawson
        display_name: Katie
        twitter: katie_rawson
        github: senderle

# Build settings
markdown: kramdown
